# This workflow will build a project with fastlane script

name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane test
